apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: train-app
  template:
    metadata:
      labels:
        app: train-app
    spec:
      containers:
      - name: train-container
        image: udzy/train-app:latest
        ports:
        - containerPort: 8000
